query GetUploadProjects(
  $where: UploadProjectWhereInput!
  $take: Int
  $skip: Int!
) {
  uploadProjects(
    where: $where
    take: $take
    skip: $skip
    orderBy: { updatedAt: desc }
  ) {
    id
    projectName
    description
    account {
      id
      name
      user {
        id
      }
    }
    projectType
    textContent
    status
    uploadLocation {
      id
      type
    }
    uploadsTo {
      id
      uploadStatus
      uploadTo
    }
    uploadsToCount
    createdAt
    updatedAt
    deletedAt
  }
}
