query GetUploadProject($where: UploadProjectWhereUniqueInput!) {
  uploadProject(where: $where) {
    id
    projectName
    description
    user {
      name
    }
    status
    uploadLocation {
      id
      type
      localLink {
        id
        path
      }
      s3Link {
        id
        key
        bucket
      }
      googleDrive {
        id
        name
        driveId
      }
    }
    uploadsTo {
      id
      uploadStatus
      uploadTo
    }
    uploadsToCount
    createdAt
    updatedAt
    deletedAt
  }
}
