query UserStatisticsReport($userId: ID!, $managedAccountInput: ManagedAccountWhereInput!) {
    userActiveProjectsCount: uploadProjectsCount(
        where: {
            AND: { account: $managedAccountInput, deletedAt: { equals: null } }
        }
    )

    createdProjectsCount: auditsCount(
        where: {
            AND: {
                tableName: { equals: "UploadProject" }
                type: { equals: "CREATE" }
                createdBy: { id: { equals: $userId } }
            }
        }
    )

    activeTasksCount: uploadsCount(
        where: {
            AND: [
                {
                    project: { account: $managedAccountInput }
                    uploadStatus: { notIn: ["FAILED", "COMPLETED"] }
                }
            ]
        }
    )

    failedTasksCount: uploadsCount(
        where: {
            AND: [
                {
                    project: { account: $managedAccountInput }
                    uploadStatus: { equals: "FAILED" }
                }
            ]
        }
    )

    completedTasksCount: uploadsCount(
        where: {
            AND: [
                {
                    project: { account: $managedAccountInput }
                    uploadStatus: { equals: "COMPLETED" }
                }
            ]
        }
    )

    totalTasksCount: uploadsCount(
        where: { AND: [{ project: { account: $managedAccountInput } }] }
    )
}
